# 启用日志
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# 启用ADC
CONFIG_ADC=y

# 启用设备检测器
CONFIG_ZMK_DEVICE_DETECTOR=y
CONFIG_ZMK_DEVICE_DETECTOR_LOG_LEVEL=4

# 启用EC11编码器
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# 启用模拟输入(摇杆)
CONFIG_ANALOG_INPUT=y
CONFIG_ANALOG_INPUT_LOG_LEVEL=4
CONFIG_ANALOG_INPUT_LOG_DBG_RAW=y
CONFIG_ANALOG_INPUT_LOG_DBG_REPORT=y

# 启用输入子系统
CONFIG_INPUT=y 